#!/bin/bash

# (cd neighborhood && git diff)
# diff --git a/neighborhood.vala b/neighborhood.vala
# index ce06286..a31673d 100644
# --- a/neighborhood.vala
# +++ b/neighborhood.vala
# @@ -179,7 +179,7 @@ namespace Netsukuku.Neighborhood
#                          warning("Neighborhood.monitor_run: " +
#                          @"DeserializeError '$(e.message)' while sending in broadcast to $(nic.mac).");
#                      }
# -                    tasklet.ms_wait(60000);
# +                    tasklet.ms_wait(2000);
#                  }
#              }
#          }
# @@ -282,7 +282,7 @@ namespace Netsukuku.Neighborhood
#                      }
#
#                      // wait a random from 28 to 30 secs
# -                    tasklet.ms_wait(Random.int_range(28000, 30000));
# +                    tasklet.ms_wait(Random.int_range(2800, 3000));
#                  }
#              }
#          }

eth_domain -i 1223_eth0 &
TEMP_1223_ETH0_PID=$!
eth_domain -i 1223_eth1 &
TEMP_1223_ETH1_PID=$!

eth_domain -i 2321_eth0 &
TEMP_2321_ETH0_PID=$!
eth_domain -i 2321_eth1 &
TEMP_2321_ETH1_PID=$!

eth_domain -i 1000_eth0 &
TEMP_1000_ETH0_PID=$!
eth_domain -i 1000_eth1 &
TEMP_1000_ETH1_PID=$!

eth_domain -i 1210_eth0 &
TEMP_1210_ETH0_PID=$!
eth_domain -i 1210_eth1 &
TEMP_1210_ETH1_PID=$!

eth_domain -i 3020_eth0 &
TEMP_3020_ETH0_PID=$!
eth_domain -i 3020_eth1 &
TEMP_3020_ETH1_PID=$!

sleep 0.3

echo Starting launches at `date +%T.%N`

./system_ntkd --topology 2,2,2,2 --firstaddr 1,2,2,3 --no-anonymize \
              \
              -p 1223 -i eth0 -i eth1 \
              \
              -t another_network,3000,0,eth0,fe:aa:aa:52:50:27,fe:aa:aa:52:50:27,1310359493 \
              \
              -t do_prepare_enter,4000,0,12345 \
              -t do_finish_enter,4010,0,12345,1310359493,0,523875,1:3:2:1,1:0:0:0 \
              \
              -t another_network,18000,1,eth1,fe:aa:aa:91:51:84,fe:aa:aa:91:51:84,1377009613 \
              \
              -t same_network,22000,1,eth1,fe:aa:aa:91:51:84,fe:aa:aa:91:51:84 \
              \
              > test_3_n_i_qspn_1223_out.txt 2>&1 &
PEER_1223_PID=$!
# Node 1223: id_0=1165049684, id_1=1379308926, fp0=570869880, eth0mac=fe:aa:aa:88:83:64, eth1mac=fe:aa:aa:84:13:82.
sleep 0.03
./system_ntkd --topology 2,2,2,2 --firstaddr 2,3,2,1 --no-anonymize \
              \
              -p 2321 -i eth0 -i eth1 \
              \
              -t another_network,3000,0,eth1,fe:aa:aa:88:83:64,fe:aa:aa:88:83:64,570869880 \
              \
              -t same_network,7000,0,eth1,fe:aa:aa:88:83:64,fe:aa:aa:88:83:64 \
              \
              > test_3_n_i_qspn_2321_out.txt 2>&1 &
PEER_2321_PID=$!
# Node 2321: id_0=999087204, fp0=1310359493, eth0mac=fe:aa:aa:91:27:19, eth1mac=fe:aa:aa:52:50:27.
sleep 0.03
./system_ntkd --topology 2,2,2,2 --firstaddr 1,0,0,0 --no-anonymize \
              \
              -p 1000 -i eth0 -i eth1 \
              \
              -t another_network,18000,0,eth0,fe:aa:aa:84:13:82,fe:aa:aa:84:13:82,1310359493 \
              \
              -t do_prepare_enter,19000,0,34251 \
              -t do_finish_enter,19010,0,34251,1310359493,0,24572,0:2:1,1:0:0 \
              \
              > test_3_n_i_qspn_1000_out.txt 2>&1 &
PEER_1000_PID=$!
# Node 1000: id_0=1128856235, fp0=1377009613, eth0mac=fe:aa:aa:91:51:84, eth1mac=fe:aa:aa:68:24:80.
sleep 0.03
./system_ntkd --topology 2,2,2,2 --firstaddr 1,2,1,0 --no-anonymize \
              \
              -p 1210 -i eth0 -i eth1 \
              \
              > test_3_n_i_qspn_1210_out.txt 2>&1 &
PEER_1210_PID=$!
# Node 1210: id_0=77606204, fp0=523161057, eth0mac=fe:aa:aa:82:64:28, eth1mac=fe:aa:aa:81:54:87.
sleep 0.03
./system_ntkd --topology 2,2,2,2 --firstaddr 3,0,2,0 --no-anonymize \
              \
              -p 3020 -i eth0 -i eth1 \
              \
              > test_3_n_i_qspn_3020_out.txt 2>&1 &
PEER_3020_PID=$!
# Node 3020: id_0=1820878047, fp0=551752794, eth0mac=fe:aa:aa:65:34:51, eth1mac=fe:aa:aa:70:80:46.
sleep 0.03

echo Done launches at `date +%T.%N`

sleep 0.3

kill $TEMP_1223_ETH0_PID $TEMP_2321_ETH1_PID
wait $TEMP_1223_ETH0_PID $TEMP_2321_ETH1_PID
eth_domain -i 1223_eth0 -i 2321_eth1 &
ETH_1223_2321_PID=$!

# node 2321: identities:identity_arc_added id# 0, dev eth1, peer_nic fe:aa:aa:88:83:64, peer_pseudonic fe:aa:aa:88:83:64
#
#   Neighborhood: [177.896778]: Signal arc_added.
#   Identities: [177.900018]: Signal identity_arc_added:
#       arc: dev eth1 peer_mac fe:aa:aa:88:83:64 peer_linklocal 169.254.33.112
#       my identity: nodeid 999087204
#       id_arc: nodeid 1165049684 peer_mac fe:aa:aa:88:83:64 peer_linklocal 169.254.33.112
#       prev_id_arc: null
#    [will be] Passing it to the module Hooking.

# node 1223:identities:identity_arc_added id# 0, dev eth0, peer_nic fe:aa:aa:52:50:27, peer_pseudonic fe:aa:aa:52:50:27
#   Neighborhood: [177.896849]: Signal arc_added.
#   Identities: [177.900200]: Signal identity_arc_added:
#       arc: dev eth0 peer_mac fe:aa:aa:52:50:27 peer_linklocal 169.254.122.80
#       my identity: nodeid 1165049684
#       id_arc: nodeid 999087204 peer_mac fe:aa:aa:52:50:27 peer_linklocal 169.254.122.80
#       prev_id_arc: null
#    [will be] Passing it to the module Hooking.

sleep 15

kill $TEMP_1000_ETH0_PID $TEMP_1223_ETH1_PID
wait $TEMP_1000_ETH0_PID $TEMP_1223_ETH1_PID
eth_domain -i 1000_eth0 -i 1223_eth1 &
ETH_1000_1223_PID=$!

# node 1223: identities:identity_arc_added id# 1, dev eth1, peer_nic fe:aa:aa:91:51:84, peer_pseudonic fe:aa:aa:91:51:84
#
#   Neighborhood: [307.917362]: Signal arc_added.
#   Identities: [307.920429]: Signal identity_arc_added:
#       arc: dev eth1 peer_mac fe:aa:aa:91:51:84 peer_linklocal 169.254.208.196
#       my identity: nodeid 1379308926
#       id_arc: nodeid 1128856235 peer_mac fe:aa:aa:91:51:84 peer_linklocal 169.254.208.196
#       prev_id_arc: null
#    [will be] Passing it to the module Hooking.

# node 1000: identities:identity_arc_added id# 0, dev eth0, peer_nic fe:aa:aa:84:13:82, peer_pseudonic fe:aa:aa:84:13:82
#
#   Neighborhood: [307.917531]: Signal arc_added.
#   Identities: [307.920475]: Signal identity_arc_added:
#       arc: dev eth0 peer_mac fe:aa:aa:84:13:82 peer_linklocal 169.254.91.64
#       my identity: nodeid 1128856235
#       id_arc: nodeid 1379308926 peer_mac fe:aa:aa:84:13:82 peer_linklocal 169.254.91.64
#       prev_id_arc: null
#    [will be] Passing it to the module Hooking.






# Dal momento che il eth_domain è attivato e abilita la comunicazione tra due pseudo-interfacce di rete di due system_ntkd,
# il modulo Neighborhood crea un arco. Al segnale neighborhood:arc_added il system_ntkd chiama add_arc di Identites. Il modulo
# Identities crea l'arco-identità principale. Al segnale identities:identity_arc_added il system_ntkd dovrà (in futuro)
# chiamare add_arc di Hooking, che per ora non c'è. Al posto del modulo Hooking, la script attiverà il task `same_network` oppure il task
# `another_network`. Questo avviene in tutti i nodi che congiungono due reti distinte.
# In questi due task (come nei relativi segnali emessi dal modulo Hooking) è necessario fornire un identificativo del IdentityArc.

# Successivamente, in tutti i nodi membri della rete guest (come primo test si presume che nella rete host
# non ci sia bisogno di nessuna migrazione) la script, sempre al posto del modulo Hooking, attiverà il task
# `do_prepare_enter` e `do_finish_enter`.



sleep 15


echo checking status...
PEER_ABORT=0
kill -0 $PEER_1223_PID || { wait $PEER_1223_PID; echo system_peer 1223 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_2321_PID || { wait $PEER_2321_PID; echo system_peer 2321 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_1000_PID || { wait $PEER_1000_PID; echo system_peer 1000 prematurely exited with $?; PEER_ABORT=1; }

kill -0 $PEER_3020_PID || { wait $PEER_3020_PID; echo system_peer 3020 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_1210_PID || { wait $PEER_1210_PID; echo system_peer 1210 prematurely exited with $?; PEER_ABORT=1; }

echo killing...

# interrupt peers one at a time

kill $PEER_1223_PID
wait $PEER_1223_PID

kill $PEER_2321_PID
wait $PEER_2321_PID

kill $PEER_1000_PID
wait $PEER_1000_PID

kill $PEER_3020_PID
wait $PEER_3020_PID

kill $PEER_1210_PID
wait $PEER_1210_PID

# Ignore errors in this shutdown. Remove any remaining local socket.
rm -f conn_169.254.*
rm -f conn_????_?
rm -f recv_????_eth?

# kill proxy demons

kill $TEMP_2321_ETH0_PID \
     $TEMP_1000_ETH1_PID $TEMP_1210_ETH0_PID $TEMP_1210_ETH1_PID $TEMP_3020_ETH0_PID $TEMP_3020_ETH1_PID

wait $TEMP_2321_ETH0_PID \
     $TEMP_1000_ETH1_PID $TEMP_1210_ETH0_PID $TEMP_1210_ETH1_PID $TEMP_3020_ETH0_PID $TEMP_3020_ETH1_PID

kill $ETH_1223_2321_PID $ETH_1000_1223_PID

wait $ETH_1223_2321_PID $ETH_1000_1223_PID

# delay for removal of local sockets (e.g. send_2232_wl0)
sleep 0.3

# check PEER_ABORT
test $PEER_ABORT -eq 0 || exit 1
