#!/bin/bash

radio_domain -i 1223_wl0 -o 2321_wl0 &
RADIO_1223_PID=$!
radio_domain -i 2321_wl0 -o 1223_wl0 &
RADIO_2321_PID=$!
sleep 0.3

echo Starting launches at `date +%T.%N`

./system_ntkd --topology 2,2,2,2 --firstaddr 1,2,2,3 --no-anonymize \
              \
              -p 1223 -i wl0 \
              \
              -t another_network,400,0,wl0,fe:aa:aa:91:27:19,fe:aa:aa:91:27:19,568638306 \
              \
              -t do_prepare_enter,1400,0,12345 \
              -t do_finish_enter,1410,0,12345,568638306,0,523875,1:3:2:1,1:0:0:0 \
              \
              > test_1_n_i_qspn_1223_out.txt 2>&1 &
PEER_1223_PID=$!
sleep 0.03
./system_ntkd --topology 2,2,2,2 --firstaddr 2,3,2,1 --no-anonymize \
              \
              -p 2321 -i wl0 \
              \
              -t another_network,400,0,wl0,fe:aa:aa:88:83:64,fe:aa:aa:88:83:64,162389070 \
              \
              -t same_network,4000,0,wl0,fe:aa:aa:88:83:64,fe:aa:aa:88:83:64 \
              \
              > test_1_n_i_qspn_2321_out.txt 2>&1 &
PEER_2321_PID=$!

echo Done launches at `date +%T.%N`

# Circa 3 secondi dopo il task do_finish_enter (t=4400) il nodo 1223 chiama get_full_etp sul nodo 2321.
# Poco prima (t=2400) il nodo 2321 ha rilevato il nuovo arco-identità.
# Il codice in enter_network rimuove la vecchia identità dopo 10 secondi che è pronta la nuova.
# Quindi facciamo il task same_network verso il tempo 4000
# e terminiamo la script in 20 secondi.

sleep 20

echo checking status...
PEER_ABORT=0
kill -0 $PEER_1223_PID || { wait $PEER_1223_PID; echo system_peer 1223 prematurely exited with $?; PEER_ABORT=1; }
kill -0 $PEER_2321_PID || { wait $PEER_2321_PID; echo system_peer 2321 prematurely exited with $?; PEER_ABORT=1; }

echo killing...

# interrupt peers one at a time

kill $PEER_1223_PID
wait $PEER_1223_PID

kill $PEER_2321_PID
wait $PEER_2321_PID

# Ignore errors in this shutdown. Remove any remaining local socket.
rm -f conn_169.254.*
rm -f conn_????_?
rm -f recv_????_wl0

# kill proxy demons
kill $RADIO_1223_PID $RADIO_2321_PID

wait $RADIO_1223_PID $RADIO_2321_PID

# delay for removal of local sockets (e.g. send_2232_wl0)
sleep 0.3

# check PEER_ABORT
test $PEER_ABORT -eq 0 || exit 1
